### ISSUE TITLE
User "pseudonyms"

### ISSUE THREAD

**Issue by paschko** [discussify/discussify.github.io#14]
Wenn mehrere Leute antworten ist absolut unklar wer was geschrieben hat (Anonymität).
Ich denke es wäre angenehmer, und das war auch mal im Gespräch, wenn die Leute Pseudonyme hätten oder zumindest die posts eingefärbt wären oder ähnliches um zu unterscheiden wer was geschrieben hat.

**Comment by DadaMonad** [comment]
Ich dachte dass jeder User einfach sich selbst mit einem Usernamen assoziieren kann. Diesen Namen kann man direkt mit der id von Yjs mappen. Ich implementiere das (später). Als Zwischenlösung kann man erstmal einfach die userid nehmen (steht in den Events drinn). Die eigene Userid steht unter `y.db.userId`.

**Comment by DadaMonad** [comment]
Completely implemented  in the `comment` branch
