### ISSUE TITLE
Presentation: Technical Part - Difficult parts

### ISSUE THREAD

**Issue by DeusProx** [discussify/discussify.github.io#18]
This issue will list difficult problems which occured during the development of our application so we can use these in our presentation

**Comment by DeusProx** [comment]
MDL is designed for static sites. MDL is using Javascript function which can upgrade elements after rendering of the view giving them a special use. Prime Examples are the drawer, tooltips and textfields.
As Angular2 is dynamic and contains a shadow dom we need to explicitely upgrade these elements ourself on changes. We solved this with using directives in elements which need to be upgraded!

**Comment by DeusProx** [comment]
Accessing some routes data which needs to be available for this route isn't actually available right from the start. So we need to check inside our template if the variable is set and stop rendering if it isn't. Also we need to subscribe to a service which gives us the value and then unsubscribes. To achieve this more easily we are creating a callback function and passing this to the service with the index of the element we want from service. (src/components/video.component.ts)

**Comment by DadaMonad** [comment]
mergen :poop:

**Comment by DeusProx** [comment]
PDF-Viewer is based on PDFJS from mozilla. it had no documentation. I couldn't get the typings with my ipv6 and the typings were also incomplete. Serious fun guys!!!!!
