### ISSUE TITLE
new build process.

### ISSUE THREAD

**Issue by DadaMonad** [discussify/discussify.github.io#6]
F*ck angular-cli.. it's slow, and annoying. I shouldn't event started with it because you need admin-rights if you want to use it on windows.

Remove it; find something better. The new tool should support minification & and gh-pages deployment. Suggestions? We shouldn't build the build chain from scratch. Better look for a cool yo project

**Comment by DeusProx** [comment]
Afaik there isn't another tool for dat. We could just stick to https://angular.io/docs/ts/latest/quickstart.html

**Comment by DeusProx** [comment]
And then serve the files with live-sever which also got a live-reload function. Atom or VS Code for automatic build.
